javamelody:
  advisor-auto-proxy-creator-enabled: false
axon:
  snapshot:
    count: 50
  axonserver:
    servers: dev-geon-axonserver-ncl.nfra.io
spring:
  data:
    es:
      host: dev-geon-es001-ncl.nfra.io
      port: 9300
      clusterName: msa-study
    mongodb:
      host: dev-geon-mongo-ncl.nfra.io
      port: 27017
server:
  port: 9090