axon:
  axonserver:
    servers: dev-geon-axonserver-ncl.nfra.io
spring:
  data:
    mongodb:
      address: mongodb://dev-geon-mongo-ncl.nfra.io:27017
      database: msa
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:./database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE

